dist: bionic
sudo: false
language: python

addons:
  postgresql: "10"

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=py36-django22
    - python: 3.7
      env: TOXENV=py37-django22
    - python: 3.8
      env: TOXENV=py38-django22
    - python: 3.6
      env: TOXENV=py36-django30
    - python: 3.7
      env: TOXENV=py37-django30
    - python: 3.8
      env: TOXENV=py38-django30

branches:
  only:
  - master


before_cache:
  - rm -rf $HOME/.cache/pip/log


cache:
  directories:
    - $HOME/.cache/pip


install:
  - pip install tox codecov


script:
  - tox


after_success:
  - codecov
